package com.btp.e2e.servlets;

//Droot.java

//Generated by https://quicktype.io



public class Droot {
	private D d;

	public D getD() {
		return d;
	}

	public void setD(D value) {
		this.d = value;
	}
}